---
- hosts: ubuntu
  become: true
  become_user: root
  become_method: sudo

  tasks:
  - name: apt-get update, upgrade, and Install Docker
    become: true
    shell: |
      apt-get update && sudo apt-get -y upgrade
      apt-get install -y apt-transport-https ca-certificates curl software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      apt-key fingerprint 0EBFCD88
      add-apt-repository  "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      apt-get update
      apt-get -y install docker-ce

    register: shellvalue

  - name: show output
    debug:
      var: shellvalue.stdout

#
# EXAMPLE: ansible-playbook -i hosts 02-ubuntu14.04-upgrade-install-docker.yml 
