---
- hosts: cs
  become_user: root
  become_method: sudo
  gather_facts: no

  vars_files:
    - "vars/params.yml"

  tasks:

    - name: create .ssh directory
      file:
        path: .ssh
        state: directory
      ignore_errors: yes
      register: shellvalue

    - name: copy keys for putty
      copy:
        src: /home/avi/ssh/authorized_keys
        dest: /home/avi/.ssh/authorized_keys
      ignore_errors: yes

    - name: apt-get update, upgrade, and Install Docker
      become: true
      shell: |
        apt-get update && sudo apt-get -y upgrade
        apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        apt-key fingerprint 0EBFCD88
        add-apt-repository  "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        apt-get update
        apt-get -y install docker-ce
